name: Publish

on:
  workflow_dispatch:
  release:
    types:
      - created
    
jobs:
  build:  
    name: Build
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        run: ls -la

  publish_repo:
    name: Uploading to PyPi
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Download wheels artifact
        uses: actions/download-artifact@v2
        run: ls -la
     

  publish_test_repo:
    name: Uploading to Test PyPi
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Download wheels artifact
        run: ls -la
    